# Generated by Django 3.1.7 on 2021-04-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210418_1837'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tag',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to='app.author', verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.question', verbose_name='вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='number',
            field=models.IntegerField(choices=[('like', 1), ('not_active', 0), ('dislike', -1)], verbose_name='Число'),
        ),
    ]
