# Generated by Django 3.1.7 on 2021-04-19 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210418_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[('like', 1), ('not_active', 0), ('dislike', -1)], verbose_name='Число')),
            ],
            options={
                'verbose_name': 'ЛайкНаОтвет',
                'verbose_name_plural': 'ЛайкиОтветов',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[('like', 1), ('not_active', 0), ('dislike', -1)], verbose_name='Число')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_like_author', to='app.author', verbose_name='автор')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.question', verbose_name='вопрос')),
            ],
            options={
                'verbose_name': 'ЛайкНаВопрос',
                'verbose_name_plural': 'ЛайкиВопросов',
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to='app.answer', verbose_name='отвт'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_like_author', to='app.author', verbose_name='автор'),
        ),
    ]
