# Generated by Django 3.1.7 on 2021-04-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210419_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
