# Generated by Django 3.1.7 on 2021-04-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210419_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['ans_date'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='date',
            new_name='ans_date',
        ),
    ]
