# Generated by Django 3.1.7 on 2021-04-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210419_1953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('author', 'question')},
        ),
    ]
