# Generated by Django 3.1.7 on 2021-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210420_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlike',
            name='number',
            field=models.IntegerField(choices=[('like', 1), ('dislike', -1)], verbose_name='Число'),
        ),
    ]
