# Generated by Django 3.1.7 on 2021-04-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210420_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rating',
            field=models.IntegerField(verbose_name='Рейтинг'),
        ),
    ]
